// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFUznXVMKSkS26z21efEXdC3_Z-w9MLaY',
    appId: '1:847364720466:web:8a70ecb927c4bea2751c8b',
    messagingSenderId: '847364720466',
    projectId: 'tallerfirebaseuniversidades',
    authDomain: 'tallerfirebaseuniversidades.firebaseapp.com',
    storageBucket: 'tallerfirebaseuniversidades.firebasestorage.app',
    measurementId: 'G-PXGS8N5C25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPq5TDKn9RRxWbGojba16drdR-zwVsD2Q',
    appId: '1:847364720466:android:ccce6b1af0cdfcf7751c8b',
    messagingSenderId: '847364720466',
    projectId: 'tallerfirebaseuniversidades',
    storageBucket: 'tallerfirebaseuniversidades.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdf65TbBAf3inK83QYVemk7HHhGXab9xM',
    appId: '1:847364720466:ios:61126e92811fdd64751c8b',
    messagingSenderId: '847364720466',
    projectId: 'tallerfirebaseuniversidades',
    storageBucket: 'tallerfirebaseuniversidades.firebasestorage.app',
    iosBundleId: 'com.example.taller4Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdf65TbBAf3inK83QYVemk7HHhGXab9xM',
    appId: '1:847364720466:ios:61126e92811fdd64751c8b',
    messagingSenderId: '847364720466',
    projectId: 'tallerfirebaseuniversidades',
    storageBucket: 'tallerfirebaseuniversidades.firebasestorage.app',
    iosBundleId: 'com.example.taller4Firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFUznXVMKSkS26z21efEXdC3_Z-w9MLaY',
    appId: '1:847364720466:web:27697a21d6054083751c8b',
    messagingSenderId: '847364720466',
    projectId: 'tallerfirebaseuniversidades',
    authDomain: 'tallerfirebaseuniversidades.firebaseapp.com',
    storageBucket: 'tallerfirebaseuniversidades.firebasestorage.app',
    measurementId: 'G-8BKRMWVVNZ',
  );
}
